name: califit_app
description: A new Flutter project for calisthenics training.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  card_swiper: ^3.0.1
  camera: ^0.10.5+9
  model_viewer_plus: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1  # A침adido

# Configuraci칩n de flutter_launcher_icons
flutter_icons:
  android: true
  ios: false  # Desactivado para iOS
  image_path: "assets/logo_app.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo_app.jpg"
  adaptive_icon_padding: true      # A침ade padding autom치tico


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/models/
    - assets/models/dominadas.glb
    - assets/images/exercises/